repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      # Security
      - id: detect-private-key
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.25.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.5
    hooks:
      - id: terraform_fmt
      - id: terragrunt_fmt
      - id: terraform_trivy
        args:
          - --hook-config=--parallelism-ci-cpu-cores=1
          - --args=--ignorefile=__GIT_WORKING_DIR__/.trivyignore
      - id: terraform_docs
        args:
          - --args=--config=.tfdocs-config.yml
          - --hook-config=--create-file-if-not-exist=true
