name: Pre-Commit Checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Run pre-commit checks
    uses: ISW-Cloud42/github-actions/.github/workflows/tofu-pre-commit.yml@main
